#!/bin/bash

# Script to compile to arduino using avr-gcc
# Dependencies: binutils, gcc-avr, avr-libc, avrdude
#   - sudo apt-get install binutils gcc-avr avr-libc avrdude arduino arduino-core

if [[$# -gt 1]]
then
    # Compile to elf
    avr-gcc -mmcu="atmega328p" -O3 $1 -o $2 -DFCPU=16000000

    # Compile to arduino
    sudo avrdude -c arduino -p m328p -P /dev/ttyUSB0 -b 57600 -U flash:w:$2

    -U update
    flash -> que memoria
else
    echo "usage: $0 <c/c++ file> --settings <path to settings file (optional)>"
fi
